
import org.testng.Assert;
import org.testng.annotations.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'WoW' at '04.05.2017 20:06' with Gradle 2.12
 *
 * @author WoW, @date 04.05.2017 20:06
 */
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Assert.assertTrue(classUnderTest.someLibraryMethod());
    }
}
