/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'WoW' at '04.05.2017 20:06' with Gradle 2.12
 *
 * @author WoW, @date 04.05.2017 20:06
 */
public class Library {
    public boolean someLibraryMethod() {
    	
    	boolean result = true;
        return result;
    }
}
